# params.yaml
index_col: 'customer_id'
target_col: 'target'
one_hot_drop: 'if_binary'
auto_class_weights: 'Balanced'
n_splits: 5
metrics: ['f1', 'roc_auc']
n_jobs: -1 
l_C: 1
l_penalty: 'l2'
drop_cols: ['id', 'begin_date', 'end_date']
